apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukuk-backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kukuk-backend
  template:
    metadata:
      labels:
        app: kukuk-backend
    spec:
      containers:
        - name: backend
          image: docker.io/andziallas/backend-kukuk:dev
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: kukuk-backend
  namespace: dev
spec:
  selector:
    app: kukuk-backend
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
