apiVersion: v1
kind: Service
metadata:
  name: kukuk-frontend
  namespace: dev
spec:
  selector:
    app: kukuk-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
