apiVersion: apps/v1
kind: Deployment
metadata:
  name: kukuk-frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kukuk-frontend
  template:
    metadata:
      labels:
        app: kukuk-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/andziallas/kukuk-frontend:dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kukuk-frontend
  namespace: dev
spec:
  selector:
    app: kukuk-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP