apiVersion: v1
kind: Service
metadata:
  name: kukuk-backend
  namespace: dev
spec:
  selector:
    app: kukuk-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
