apiVersion: v1
kind: Service
metadata:
  name: kukuk-backend
  namespace: prod
spec:
  selector:
    app: kukuk-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
